---
- hosts: all
  become: true
  tasks:
    - name: Init a new swarm with default parameters
      docker_swarm:
        state: present
      register: op

    - name: Output in debug module
      debug:
        msg : "{{ op.swarm_facts.JoinTokens.Worker }}"
...
