---
tosca_definitions_version: tosca_simple_yaml_1_3

description: Service Template under construction

imports:
  - relationshiptypes/token_transfer.yaml
  - nodetypes/swarm_leader/swarm_leader.yaml
  - nodetypes/swarm_worker/swarm_worker.yaml

topology_template:
  node_templates:
    fog-node-1:
      type: tosca.nodes.Compute
      attributes:
        private_address: 192.168.0.112
        public_address: 192.168.0.112

    docker-swarm-leader:
      type: fog.docker.SwarmLeader
      requirements:
        - host: fog-node-1

    fog-node-2:
      type: tosca.nodes.Compute
      attributes:
        private_address: 192.168.0.222
        public_address: 192.168.0.222

    # test-file-1:
    #   type: hello_type
    #   requirements:
    #     - host: fog-node-2
    #     - leader: docker-swarm-leader

    docker-swarm-worker-1:
      type: fog.docker.SwarmWorker
      properties:
        ip_addr: 192.168.0.222
        leader_ip_addrs_port:
          - "192.168.0.112:2377"
      requirements:
        - host: fog-node-2
        - leader: docker-swarm-leader

    fog-node-3:
      type: tosca.nodes.Compute
      attributes:
        private_address: 192.168.0.111
        public_address: 192.168.0.111

    # test-file-2:
    #   type: hello_type
    #   requirements:
    #     - host: fog-node-3
    #     - leader: docker-swarm-leader

    docker-swarm-worker-2:
      type: fog.docker.SwarmWorker
      properties:
        ip_addr: 192.168.0.111
        leader_ip_addrs_port:
          - "192.168.0.112:2377"
      requirements:
        - host: fog-node-3
        - leader: docker-swarm-leader

  outputs:
    output_worker_token_attribute:
      value: { get_attribute: [docker-swarm-leader, worker_token] }
    output_manager_token_attribute:
      value: { get_attribute: [docker-swarm-leader, manager_token] }
